//user actions
export const LOGIN_ACTION = "LOGIN";
export const LOGOUT_ACTION = "LOGOUT";

export const GET_USERS_ACTION = "GET_USERS";
export const SET_SEND_PASSWORD_LINK_ACTION = "SET_SEND_PASSWORD_LINK";
export const SET_PASSWORD_ACTION = "SET_PASSWORD";
export const CREATE_USER_ACTION = "CREATE_USER";
export const UPDATE_USER_ACTION = "UPDATE_USER";
export const DEACTIVATE_USER_ACTION = "FIRE_USER";
export const USER_ERROR_ACTION = "USER_ERROR";

export const MANAGE_USERS_ERROR_ACTION = "MANAGE_USERS_ERROR";

//time tracker (work session) actions
export const WORK_SESSION_ERROR_ACTION = "WORK_SESSION_ERROR";
export const GET_ACTIVE_WORK_SESSION_ACTION = "GET_ACTIVE_WORK_SESSION";
export const SET_END_WORK_SESSION_ACTION = "SET_END_WORK_SESSION";
export const CREATE_WORK_SESSION_ACTION = "CREATE_WORK_SESSION_ACTION";
export const GET_USER_WORK_SESSIONS_ACTION = "GET_USER_WORK_SESSIONS";
export const UPDATE_WORK_SESSION_ACTION = "UPDATE_WORK_SESSION";
export const DELETE_WORK_SESSION_ACTION = "DELETE_WORK_SESSION";

//holidays
export const HOLIDAYS_ERROR_ACTION = "HOLIDAYS_ERROR";
export const GET_HOLIDAYS_ACTION = "GET_HOLIDAYS";
export const CREATE_HOLIDAY_ACTION = "CREATE_HOLIDAY";
export const UPDATE_HOLIDAY_ACTION = "UPDATE_HOLIDAY";
export const DELETE_HOLIDAY_ACTION = "DELETE_HOLIDAY";

//vacations
export const VACATION_ERROR_ACTION = "VACATION_ERROR";
export const GET_VACATIONS_BY_USER_ID_ACTION = "GET_VACATIONS_BY_USER_ID";
export const GET_VACATION_INFO_BY_USER_ID_ACTION = "GET_VACATION_INFO_BY_USER_ID";