//user actions
export const LOGIN_ACTION = "LOGIN";
export const LOGOUT_ACTION = "LOGOUT";
export const USER_FOUND_ACTION = "USER_FOUND";
export const USER_ERROR_ACTION = "USER_ERROR";
export const GET_USERS_ACTION = "GET_USERS";


//time tracker (work session) actions
export const WORK_SESSION_ERROR_ACTION = "WORK_SESSION_ERROR";
export const GET_ACTIVE_WORK_SESSION_ACTION = "GET_ACTIVE_WORK_SESSION";
export const SET_END_WORK_SESSION_ACTION = "SET_END_WORK_SESSION";
export const CREATE_WORK_SESSION_ACTION = "CREATE_WORK_SESSION_ACTION";